source ~/.shell/profile

# Play well with others, source global definitions.
if [ -f /etc/bashrc ]; then
	source /etc/bashrc
fi

# Set locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source ~/.bash/yyyymmdd/yyyymmdd.sh

# On OSX do
#     brew install bash
#     sudo -s
#     echo /usr/local/bin/bash >> /etc/shells
#     chsh -s /usr/local/bin/bash
# See also https://johndjameson.com/blog/updating-your-shell-with-homebrew/

# Prompt displays git branch.

export GITAWAREPROMPT=~/.bash/git-aware-prompt
source $GITAWAREPROMPT/main.sh

export PS1="\u@\h \[$txtgrn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "

if [ -f ~/.software/etc/profile ]; then
	source ~/.software/etc/profile
fi

source ~/.bash/bb-clone/fun.sh
source ~/.bash/gh-clone/fun.sh

source ~/.bash/kiss-literate-programming/klp.sh

source ~/.bash/git-hub/.rc

# On OSX, enable brew completion
BREW=$(which brew)

if test $BREW
then
	BREW_BASH_COMPLETION=$(brew --prefix)/etc/bash_completion

	if [ -f $BREW_BASH_COMPLETION ]
	then
		source $BREW_BASH_COMPLETION
	fi

	unset BREW
	unset BREW_BASH_COMPLETION
fi

export PATH=~/.bash/git-number:$PATH

NVIM_COLORSCHEMES=("jellybeans" "spartan" "zenburn")
NVIM_COLORSCHEME_FILE=~/.config/nvim/config/colorscheme.vim
NVIM_COLORSCHEME=${NVIM_COLORSCHEMES[$RANDOM % ${#NVIM_COLORSCHEMES[@]} ]}
rm $NVIM_COLORSCHEME_FILE
cat <<NVIM_COLORSCHEME > $NVIM_COLORSCHEME_FILE
" Do not edit this file, it is generated by ~/.bashrc
colorscheme $NVIM_COLORSCHEME
NVIM_COLORSCHEME

# How to use an ssh-agent:
#
# 1. Create an ssh key, see
#
#    http://g14n.info/2013/04/getting-started-with-git-shell/#ssh-public-key-based-authentication
#
#    but, do NOT leave the passphrase empty.
#
# 2. Copy script
#
#    from ~/.bash/ssh-agent
#    to ~/.ssh/agent
#
if [ -f ~/.ssh/agent ]; then
	. ~/.ssh/agent
fi

source ~/.shell/z/z.sh

source ~/.bash/completion/npm

# Load local profile.
if [ -f ~/.local.bashrc ]; then
	source ~/.local.bashrc
fi

source ~/.bash/dir/fun.sh

NPM_CONFIG_PREFIX=~/.npm-global
mkdir -p $NPM_CONFIG_PREFIX
export NPM_CONFIG_PREFIX
export PATH=${NPM_CONFIG_PREFIX}/bin:$PATH
